export const PRESETS = Object.freeze({
  DEEP_BLUE: Object.freeze({
    label: 'Deep Blue',
    flowEnabled: false,
    roomEnabled: true,
    fogEnabled: true,
    lighting: Object.freeze({
      keyIntensity: 3.4,
      rimIntensity: 3.15,
      fillIntensity: 1.16,
      centerIntensity: 1.34,
      flowSpotIntensity: 0,
      flowPulseIntensity: 0,
      flowSpeed: 1.0,
      flowAngle: Math.PI / 12,
      spotFocus: 0.5,
    }),
    room: Object.freeze({
      color: 0x060c18,
      emissiveIntensity: 0.29,
      backgroundColor: null,
    }),
    fog: Object.freeze({
      enabled: true,
      color: 0x050814,
      mode: 'linear',
      density: 0,
      near: 8,
      far: 38,
    }),
    motion: Object.freeze({
      groupRot: 0.03,
      driftAmp: 0.03,
    }),
    grid: Object.freeze({
      gridCount: 3,
      gridSpacing: 1.75,
    }),
  }),
  FLOW_SOFT: Object.freeze({
    label: 'Soft Flow',
    flowEnabled: true,
    roomEnabled: true,
    fogEnabled: true,
    lighting: Object.freeze({
      keyIntensity: 3.25,
      rimIntensity: 2.3,
      fillIntensity: 1.41,
      centerIntensity: 1.08,
      flowSpotIntensity: 2.5,
      flowPulseIntensity: 1.22,
      flowSpeed: 0.9,
      flowAngle: Math.PI / 12,
      spotFocus: 1.0,
    }),
    room: Object.freeze({
      color: 0x060c18,
      emissiveIntensity: 0.32,
      backgroundColor: null,
    }),
    fog: Object.freeze({
      enabled: true,
      color: 0x050814,
      mode: 'linear',
      density: 0,
      near: 12,
      far: 60,
    }),
    motion: Object.freeze({
      groupRot: 0.03,
      driftAmp: 0.03,
    }),
    grid: Object.freeze({
      gridCount: 3,
      gridSpacing: 1.75,
    }),
  }),
  FLOW_STRONG: Object.freeze({
    label: 'Strong Flow',
    flowEnabled: true,
    roomEnabled: true,
    fogEnabled: true,
    lighting: Object.freeze({
      keyIntensity: 3.25,
      rimIntensity: 2.5,
      fillIntensity: 1.4,
      centerIntensity: 1.3,
      flowSpotIntensity: 2.7,
      flowPulseIntensity: 1.34,
      flowSpeed: 1.2,
      flowAngle: Math.PI / 14,
      spotFocus: 0.92,
    }),
    room: Object.freeze({
      color: 0x060c18,
      emissiveIntensity: 0.3,
      backgroundColor: null,
    }),
    fog: Object.freeze({
      enabled: true,
      color: 0x050814,
      mode: 'linear',
      density: 0,
      near: 10,
      far: 52,
    }),
    motion: Object.freeze({
      groupRot: 0.03,
      driftAmp: 0.03,
    }),
    grid: Object.freeze({
      gridCount: 3,
      gridSpacing: 1.75,
    }),
  }),
});
